[database]
url = "ws://localhost:8080/rpc"
user = "root"
pass = "root"
namespace = "fyp"
database = "violation_record"

[cam]
url = "localhost"
port = 8877

[server]
url = "localhost"
port = 8787

[discord]
ip= "127.0.0.1"
port = 8572
token = "MTE4ODQyNTM0MDI1MTU1Mzg2Mw.Guojnj.J_FHmL2aSbdr1ZJPFMlNwNgryorIRZmboN2AYk"
guild_id = 1136972746698522664
log_channel = "log"
interaction_user_id = 688711207087374365