[cam]
url = "localhost:8878"
port = 8878

[server]
url = "localhost:8788"
port = 8788

[tim_cam]
url = "localhost:8877"
port = 8877

[tim_server]
url = "localhost:8787"
port = 8787

[web]
# url = "05wbdt0x-8007.asse.devtunnels.ms"
url = "localhost:8007"
index = "index"
port = 8007

[user_database]
url = "ws://localhost:8080/rpc"
user = "root"
pass = "root"
namespace = "fyp"
database = "violation_record"


# [cam]
# url = "localhost"
# port = 8878

# [web]
# url = "05wbdt0x-8007.asse.devtunnels.ms"
# # url = "29zpmw89-8007.asse.devtunnels.ms"
# # url = "localhost:8007"
# index = "index"
# port = 8007

# [server]
# url = "localhost"
# port = 8788

# [user_database]
# url = "ws://localhost:8080/rpc"
# user = "root"
# pass = "root"
# namespace = "fyp"
# database = "violation_record"
